#!/usr/bin/env bash

# ! GENERATED BY AI, I don't have the time to write this from scratch, but it's not a critical part of the repo

set -euo pipefail

cd ..

filter="${1:-*}"
training_type="${2:-Intra}"
max_parallel="${3:-6}"

if ! [[ "$max_parallel" =~ ^[0-9]+$ ]] || [ "$max_parallel" -lt 1 ]; then
  echo "max_parallel must be a positive integer, got: $max_parallel" >&2
  exit 1
fi

# Tracks if any jobs were launched
any_launched=0
# Only define pids array if at least one script matches, to avoid unbound variable
declare -a pids

echo "Checking for configs in configs/${training_type}/${filter}/*.yaml"
echo "found $(find configs/${training_type}/${filter}/*.yaml | wc -l) configs"

echo "Current directory: $(pwd)"

for script in configs/${training_type}/${filter}/*.yaml; do
  [ -f "$script" ] || continue

  any_launched=1

  while [ "$(jobs -pr | wc -l | tr -d '[:space:]')" -ge "$max_parallel" ]; do
    sleep 1
  done

  echo "Running $script"
  mkdir -p logs_parallel/$(dirname $script)
  uv run main.py "$script" --force > logs_parallel/$(dirname $script)/$(basename $script).log 2>&1 &
  # For testing uncomment below:
  # sleep 2 > /dev/null &
  pids+=("$!")
done

failed=0
if (( any_launched )); then
  for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
      failed=1
    fi
  done
fi

exit "$failed"
